### ISSUE TITLE
Optimizing dictionary data structures fails when using a partially initialized function

### ISSUE THREAD

**Issue by enrico-stauss** [Lightning-AI/litdata#120]
When passing `fn=partial(my_func, arg1=arg1)` to optimize, the line linked below will yield only the keys of the dictionary that `my_func`returns. I avoided the issue by not using partial for my usecase but I`d consider this a bug.

Kind regards :)

https://github.com/Lightning-AI/litdata/blob/a09de861eadcb8389d0bc3065a901113c9e72a5f/src/litdata/processing/functions.py#L138

**Comment by tchaton** [comment]
Hey @enrico-stauss, Could you try out the latest version of litdata ?

**Comment by tchaton** [comment]
This has been fixed.
