### ISSUE TITLE
Subsample StreamingDataset

### ISSUE THREAD

**Issue by yhl48** [Lightning-AI/litdata#135]
## 🚀 Feature
`StreamingDataset` has enabled fast data reading, which is amazing when we have a large dataset. However, currently, it does not support reading just a fraction of data, and simple methods such as slicing the dataset does not work with `StreamingDataset`.

Could we have a feature to support this? Thanks. 

cc: @tchaton

**Comment by abysmalocean** [comment]
I am also interested in this feature. any ideas?

**Comment by tchaton** [comment]
Hey @abysmalocean The feature is being worked on right now: https://github.com/Lightning-AI/litdata/pull/161. Feel free to review it and give your ideas ;)

**Comment by abysmalocean** [comment]
Apologies for the inquiry, but the sub-sampling occurs at the `StreamingDataset` level. 
Once the StreamingDataset is corrected, the sub-sampled dataset cannot be altered from the StreamingDataLoader perspective, correct? Am I right?
for example. the `StreamingDataLoader` will iterative over the same sub-data set during training right?
