### ISSUE TITLE
Training slowed down as time progress with litdata streaming dataset

### ISSUE THREAD

**Issue by ouj** [Lightning-AI/litdata#138]
## 🐛 Bug

Training slowed down as time progress. 

### To Reproduce

Unfortunately, I don't know what a good way to reproduce this is. This happens to certain datasets. 

The dataset in question is about 2TB in size on S3. 

It is prepared with 
```
    optimize(
        fn=processor,  # type: ignore
        inputs=inputs,
        output_dir=args.output_path,
        num_workers=args.num_workers,
        compression="zstd",  # The compression algorithm to use.
        chunk_bytes="128MB",  # The maximum number of bytes to write into a data chunk.
        reorder_files=False,
    )
```

The training was run on Sagemaker using a single A100 machine with DDP. 

Here is one run 

![training_epoch](https://github.com/Lightning-AI/litdata/assets/1028148/732511d1-cec1-47c9-8130-70352513d04c)

We can see that each epoch runs slower and slower.

I am also monitoring the system metrics and can see that CPU and GPU utilization dropping while memory usage remain very low.

![Screenshot 2024-05-22 at 10 17 39 AM](https://github.com/Lightning-AI/litdata/assets/1028148/4efd0309-fa30-4f95-85c1-04a0e45ebfc3)

### Expected behavior

The speed of training is consistent across all epochs. 

### Environment

- PyTorch Version (e.g., 1.0): 2.3.0
- OS (e.g., Linux): Ubuntu 22.4
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source): N/A
- Python version: 3.11
- CUDA/cuDNN version: 12.4.1
- GPU models and configuration: A100

**Comment by ouj** [comment]
I am going to try what @tchaton suggested to reload the dataloader each epoch.

I am also going to try to increase the on-disk cache by a lot to see if it helps

**Comment by tchaton** [comment]
Hey @ouj Do you think you could provide a reproducible script for me to debug this on my end too ?

**Comment by tchaton** [comment]
@ouj I am curious. Have you tried Lightning.AI for your training. If you were, I could help you to debug this more in depth.

**Comment by ouj** [comment]
I figured out what was the issue. In some cases, I accidentally set num_worker=0. 

Setting num_worker=1 will solve the problem.

**Comment by tchaton** [comment]
Great to hear @ouj thanks ;)
