### ISSUE TITLE
Ram increasing during first epoch of training

### ISSUE THREAD

**Issue by rakro101** [Lightning-AI/litdata#141]
## 🐛 Bug

During training, in the first epoch the ram increase.
For example starting with 27 GB aber 10 % of first epoch it is up 40GB ...
I do not expect this ram increase when streaming data. 

### To Reproduce
See https://github.com/Lightning-AI/litdata/issues/140

1. use a dataset and convert it to litdata format
2. start a training, where in one epoch you go to each sample for the train data set once
3. see the ram increase

#### Code sample

See https://github.com/Lightning-AI/litdata/issues/140

### Expected behavior

Ram should no be increasing due the full first epoch.
### Environment

See https://github.com/Lightning-AI/litdata/issues/140

### Additional context

see See https://github.com/Lightning-AI/litdata/issues/140

**Comment by jackcyc** [comment]
I also encountered a similar issue while training an ImageNet classification model on a resource-limited PC. Specifically, I found that the prefetch_factor of StreamingDataLoader is set to 10 by default when num_worker > 0.

https://github.com/Lightning-AI/litdata/blob/d5eff393cd17ba4f789fa846788f40b5ca4d0779/src/litdata/streaming/dataloader.py#L604

This default value appears to differ from what is described in the StreamingDataLoader docstring and also PyTorch's DataLoader default.

Manually setting the prefetch_factor to a smaller number, like 2, significantly reduced the RAM usage.

**Comment by deependujha** [comment]
Thanks for pointing out wrong default value in docstring, it'll be fixed soon.

https://github.com/Lightning-AI/litdata/blob/d5eff393cd17ba4f789fa846788f40b5ca4d0779/src/litdata/streaming/dataloader.py#L533C8-L537C74

Did you try values in the middle, like 5-6? If yes, please share your experience.

It'll help in fixing this if something needs to be done.

**Comment by tchaton** [comment]
Hey @jackcyc. Yes, it seems to be fine with LLM pre-training and ImageNet but it is true it is data specific. This was a tuning I did to accelerate training as I noticied lower GPU utilization.

If you feel like the value should be put back to something lower, feel free to make a PR and we will merge it.
