### ISSUE TITLE
Support splitting datasets

### ISSUE THREAD

**Issue by robmarkcole** [Lightning-AI/litdata#145]
## 🚀 Feature

Support splitting of datasets

### Motivation

My dataset doesn't have train/val/test split and I get `RuntimeError: The provided dataset should be either an instance of StreamingDataset or CombinedStreamingDataset. Found <torch.utils.data.dataset.Subset object>` when using random splitting. I would like this workflow supported

### Pitch

The approach above is compatible with streaming datasets

### Alternatives

Pre splitting the dataset

### Additional context

- A StreamingDataset is described by its index.json. The chunks are loaded from the file into a list there: https://github.com/Lightning-AI/litdata/blob/main/src/litdata/streaming/config.py#L56
[3:58](https://pytorch-lightning.slack.com/archives/D05N141TKF0/p1716994719839439)
- We could have a utility that takes a StreamingDataset and return multiple ones with sliced chunks list.
- Overlaps https://github.com/Lightning-AI/litdata/issues/135

**Comment by deependujha** [comment]
Hey @tchaton, can I work on this?

**Comment by tchaton** [comment]
Hey @deependujha Sure. Go for it.

**Comment by tchaton** [comment]
Hey @deependujha any updates ?

**Comment by yhl48** [comment]
@tchaton I can try my hand at this

**Comment by deependujha** [comment]
I'm working on it, and need some guidance if I'm going in right direction.

At this line: https://github.com/Lightning-AI/litdata/blob/935eef59349c5e3fb785ee8ea6d0e6382d2a9728/src/litdata/streaming/dataset.py#L275C5-L283C1

```python
    def __getitem__(self, index: Union[ChunkedIndex, int]) -> Any:
        if self.cache is None:
            self.worker_env = _WorkerEnv.detect()
            self.cache = self._create_cache(worker_env=self.worker_env)
            self.shuffler = self._create_shuffler(self.cache)
        if isinstance(index, int):
            index = ChunkedIndex(index, self.cache._get_chunk_index_from_index(index))
# ---------------------------------------------------------------------------------------------------------------------------
        if isinstance(index, slice):
            start, stop, step = index.indices(len(self))
            _my_indices = list(range(start, stop, step))
            _my_cache_indices = [ChunkedIndex(idx, self.cache._get_chunk_index_from_index(idx)) for idx in _my_indices]
            return [self.cache[chnk_idx] for chnk_idx in _my_cache_indices]
# --------------------------------------------------------------------------------------------------------------------------
        return self.cache[index]
```

I added a few lines of code to support slicing. It has worked fine for me.
![Screenshot from 2024-06-05 13-20-06](https://github.com/Lightning-AI/litdata/assets/76887609/e479ec5d-73a9-4947-92ac-546d467bba16)

I'm unsure what will happen if the slice is too big, but, am I on the right path?

And, just to be sure, I need to create a method that will take a `StreamingDataset` and a list summing up to 1, and return a `list of StreamingDataset` to support splitting dataset?

**Comment by deependujha** [comment]
> @tchaton I can try my hand at this

Sorry, I didn't saw your msg and I was writing mine for last 30 min 😞.
