### ISSUE TITLE
Dataset weightage bug

### ISSUE THREAD

**Issue by yhl48** [Lightning-AI/litdata#185]
It doesn’t look like this line is doing what’s intended based on the comment, all datasets are given equal weightage here 

https://github.com/Lightning-AI/litdata/blob/d5eff393cd17ba4f789fa846788f40b5ca4d0779/src/litdata/streaming/combined.py#L74

cc: @tchaton

**Comment by yhl48** [comment]
For context, I started looking into this code because I consistently get periodic sine-like validation loss when combining two datasets, but the issue disappeared when I manually shuffled and combined them into a single dataset. The two datasets have a 1:3 size ratio. 

I am not sure if L74 is a bug, and if it is indeed a bug, I am not sure if correcting that would solve the validation loss issue. Anyways, I thought it would be good to have a discussion here 🙂

**Comment by tchaton** [comment]
Oh yes, we should take the inverse of the length of each dataset. Good catch.
