### ISSUE TITLE
Add support for Mosaic Streaming WDS data format

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/litdata#195]
### Motivation

The format are similar and it would be nice to be able to use a Mosaic streaming dataset with LitData.

**Comment by bhimrazy** [comment]
Hi @tchaton,

I wanted to learn more about this feature to see if I could contribute. 
Is it related to making the `StreamingDataLoader` compatible with the `StreamingDataset` from Mosaic?

Or is it about converting the StreamingDataset instance from Mosaic to litdata and then consuming it further, 
or is it something else?

Thank you!

**Comment by tchaton** [comment]
Hey @bhimrazy,

Great question. Here is what we want to achieve.

Generate a MDS dataset with Mosaic ML

```python
import numpy as np
from PIL import Image
from streaming import MDSWriter

# Local or remote directory in which to store the compressed output files
data_dir = 'path-to-dataset'

# A dictionary mapping input fields to their data types
columns = {
    'image': 'jpeg',
    'class': 'int'
}

# Shard compression, if any
compression = 'zstd'

# Save the samples as shards using MDSWriter
with MDSWriter(out=data_dir, columns=columns, compression=compression) as out:
    for i in range(10000):
        sample = {
            'image': Image.fromarray(np.random.randint(0, 256, (32, 32, 3), np.uint8)),
            'class': np.random.randint(10),
        }
        out.write(sample)
```

And enable to read it with LitData.

```python
from litdata import StreamingDataset, StreamingDataloder

# Remote path where full dataset is persistently stored
remote = 's3://my-bucket/path-to-dataset'

# Local working dir where dataset is cached during operation
local = '/tmp/path-to-dataset'

# Create streaming dataset
dataset = StreamingDataset(local=local, remote=remote, shuffle=True)

# Let's see what is in sample #1337...
sample = dataset[1337]
img = sample['image']
cls = sample['class']

# Create PyTorch DataLoader
dataloader = DataLoader(dataset)
```

We have roughly the same logic to encode & decode the chunks (different serializers). The main difference comes from the way the StreamingDataset handles pre-fetching the data.

**Comment by tchaton** [comment]
And @bhimrazy, if you have to copy any code from Mosaic Streaming repo, let's make sure to include full credits and the reason why the code is copied over.

**Comment by bhimrazy** [comment]
Sure, @tchaton. 
Thanks for providing the context here. 
I'll go through it.

**Comment by tchaton** [comment]
Awesome @bhimrazy. Keep me updated if you are blocked.

**Comment by tchaton** [comment]
Hey @bhimrazy. How is it going ?

**Comment by bhimrazy** [comment]
> Hey @bhimrazy, how's it going?

Hi @tchaton,

I'm currently reviewing the codebase to gain a deeper understanding of the encoding and decoding processes, caching, etc. Progress has been slow due to time constraints.

I will keep you updated on the Discord channel if I have any questions. 

Thank you for checking.

**Comment by bhimrazy** [comment]
By the way, I learned something new: `zstd` compression. I didn't know about that.
