### ISSUE TITLE
Add support for encrypting / decrypting the chunks + API Keys

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/litdata#197]
### Motivation

Add support for encrypting & decrypting the chunks to enable users to consume the data outside anywhere safely.

The data would be decrypted in RAM.

**Comment by bhimrazy** [comment]
Hi @tchaton,

I'm interested in learning more about this feature and exploring how I might be able to contribute. 
Thanks for your help!

**Comment by tchaton** [comment]
Hey @bhimrazy. Go for it.

**Comment by tchaton** [comment]
Hey @bhimrazy,

I think we could have something like this.

```
optimize(

	encryption=Entryption(password="...", level="sample|chunk")

```

And we could offer other encryption format such as RSA, etc..

**Comment by bhimrazy** [comment]
Thank you, @tchaton, for providing the examples. They are extremely helpful. 

For the symmetric encryption option, I am considering using [Fernet (symmetric encryption)](https://cryptography.io/en/latest/fernet/).

What are your thoughts on using Fernet for this purpose?

**Comment by bhimrazy** [comment]
Hi @tchaton,

Just checking if we need to move the 'API Keys' part from this issue to a new one, as #219 got closed for handling the encryption/decryption.
