### ISSUE TITLE
“StreamingDataset”

### ISSUE THREAD

**Issue by knighton** [Lightning-AI/litdata#21]
![IMG_3748](https://github.com/Lightning-AI/litdata/assets/2980246/63bc7a2c-850d-42c4-b665-2fc46a875a06)

**Comment by tchaton** [comment]
Hey James Knighton @knighton . 

![image](https://github.com/Lightning-AI/litdata/assets/12861981/06088a5e-65a8-4d74-ad2f-1eae21e57c08)
