### ISSUE TITLE
Append data to pre-optimized dataset

### ISSUE THREAD

**Issue by tchaton** [Lightning-AI/litdata#23]
### Description & Motivation

It's not uncommon to have to update the data one is training on or computing embeddings on etc. We could support appending data to an optimized (chunked) dataset.
Appending alone is sufficient, removal is more specific and can be performed by rerunning through the samples with a map and creating a new dataset from it.

### Pitch

When we map or optimize specifying a target location, add ability to append to existing chunks (through a `mode="append"` argument or something along these lines).

### Alternatives

The alternative is creating a new dataset and compose with the previous one during iteration. However composition is not trivial because we need to make sure we are drawing each sample once from each and then avoid bumping into StopIteration. We would need to add a specific mode to composed dataset.

If the data added is misaligned with the chunk size and appending happens often it would create a suboptimal dataset after a while, that would need to be compacted into a single one by iterating sequentially. This could be a further alternative: a utility where you pass a list of datasets and create a single dataset by iterating through all of them.

cc @borda @tchaton

Moved from https://github.com/Lightning-AI/pytorch-lightning/issues/19519, submitted by @lantiga

**Comment by isidentical** [comment]
this is essentially one of the main blockers that'd switch us from switching to litdata, as for training cascaded models we need to constantly amend an existing set of data (consider [img, caption] pairs, but then we introduce 256x256 latents, then 512x512 latents etc))

**Comment by tchaton** [comment]
Hey @isidentical. Would you be interested to add the feature. It shouldn't be too hard to do.

**Comment by deependujha** [comment]
Hi, I'm interested in working on this feature. But, before that, I must ensure I've understood it correctly.

The current behavior for `optimize` is:
```python
    optimize(
        fn=random_images,
        inputs=list(range(1000)),
        output_dir="my_dataset", 
        num_workers=4,
        chunk_bytes="64MB" 
    )

    ds = StreamingDataset("my_dataset")
    assert len(ds) == 1000

   # again calling `optimize` will **overwrite** existing optimized dataset
    optimize(
        fn=random_images,
        inputs=list(range(10)),
        output_dir="my_dataset",
        num_workers=4,
        chunk_bytes="64MB",
    )

    ds = StreamingDataset("my_dataset") 
    assert len(ds) == 10
```

So, we have to add a new argument to `optimize` called `mode='append' or mode='overwrite'` that will do the expected.

---

But, if this is what we want, we can create multiple optimized datasets and then use `CombinedStreamingDataset`:
```python
    optimize(
        fn=random_images,
        inputs=list(range(1000)),
        output_dir="my_dataset-1", 
        num_workers=4,
        chunk_bytes="64MB" 
    )

    optimize(
        fn=random_images,
        inputs=list(range(10)),
        output_dir="my_dataset-2", 
        num_workers=4,
        chunk_bytes="64MB" 
    )

    train_datasets = [
        StreamingDataset(
            input_dir="my_dataset-1",
        ),
        StreamingDataset(
            input_dir="my_dataset-2",
        ),
    ]
    combined_dataset = CombinedStreamingDataset(datasets=train_datasets, seed=42)

    assert len(combined_dataset) == 1000 + 10 
```

---

So, what exactly do we want? 
1. `append` argument in `optimize` function.
2. Just like we have `CombinedStreamingDataset`, we should have a `CombinedOptimizeDataset`.

Or something else.

And, a silly question: any real-world example when we want to update/ modify data in each epoch when training a model? ChatGPT gave the example of `Online learning`.

**Comment by tchaton** [comment]
Hey @deependujha We want 1. The CombinedStreamingDataset has many drawbacks where it creates multiple threads, doesn't have good synchronisation points, etc.. 
Things are always faster and more native when using a single dataset source.
