### ISSUE TITLE
Streaming from azure blob storage

### ISSUE THREAD

**Issue by jaehwana2z** [Lightning-AI/litdata#242]
### Motivation

Do you have a plan for supporting streaming from azure blob storage?  Issue #101 requested for GCS, and I am wondering if Azure Blob Storage integration is also a possibility

**Comment by tchaton** [comment]
Hey @jaehwana2z. It is super easy to add. Do you want to make a PR ?  Just need to add support for an Azure Client as the one for GCP: https://github.com/Lightning-AI/litdata/blob/main/src/litdata/streaming/downloader.py#L90.
