### ISSUE TITLE
Which image storage format to use - PIL or numpy (or torch) ?

### ISSUE THREAD

**Issue by cgebbe** [Lightning-AI/litdata#256]
## Question

Most example seem to store images in the `PIL` format or `numpy` format. The example at https://lightning.ai/lightning-ai/studios/download-stream-400m-images-text uses JPEG-compression.

Are there any general best practices, e.g. PIL leading to a faster data loading usually?

**Comment by tchaton** [comment]
Hey @cgebbe. The smaller, the better as it is usually slower to download than to de-serialize images. It is why I am showing examples with JPEG quality 90% usually. Plus, LitData uses lit-turbo to deserialize, so it is quite fast.
