### ISSUE TITLE
StreamingDataset cannot load one-element, one-dimensional tensors

### ISSUE THREAD

**Issue by bfolie** [Lightning-AI/litdata#294]
## 🐛 Bug

I'm applying Litdata's `optimize` method to a dataset of one-dimensional tensors. I get an error when trying to use a `StreamingDataset` on the optimized data. 

### To Reproduce

The following script will reproduce the error

```
from lightning.data import optimize, StreamingDataset
import torch

def process(x):
    item = torch.rand(size=(10,))
    yield (item,)

if __name__ == "__main__":
    data_dir = "litdata_bug_repro"
    optimize(
        fn=process,
        inputs=list(range(100)),
        num_workers=1,
        output_dir=data_dir,
        chunk_bytes="64MB"
    )

    dataset = StreamingDataset(data_dir)
    dataset[0]
```

Here's the error

```
litdata_bug_repro.py 20 <module>
dataset[0]

dataset.py 326 __getitem__
self.cache = self._create_cache(worker_env=self.worker_env)

dataset.py 171 _create_cache
cache._reader._try_load_config()

reader.py 223 _try_load_config
self._config = ChunksConfig.load(

config.py 251 load
return ChunksConfig(

config.py 63 __init__
self._validate_item_loader()

config.py 265 _validate_item_loader
raise ValueError("Please, use Cache(..., item_loader=TokensLoader(block_size=...))")

ValueError:
Please, use Cache(..., item_loader=TokensLoader(block_size=...))

```

### Environment

- Litdata version 0.2.21 (though I first noticed it on 0.2.16)
- Python version 3.11
- PyTorch Version 2.0.1+cpu.cxx11.abi
- OS Ubuntu

### Additional context

I've only seen the error for single-element tuples containing one-dimensional tensors. All of the following work as expected
```
def process(x):
    item = np.random.normal(size=(10,))  # one-dimensional numpy array
    yield (item,)
```

```
def process(x):
    item = torch.rand(size=(10,))
    yield (item, item)  # Multiple elements
```
```
def process(x):
    item = torch.rand(size=(10,10))  # Higher-dimensional tensor
    yield (item,)
```

**Comment by tchaton** [comment]
Hey, 1D array are handled differently in LitData and currently a hack to unlock LLM pre-training. What's your usecase ?

**Comment by tchaton** [comment]
Makes sense. I have an idea. I will try it out.

**Comment by tchaton** [comment]
Hey @bfolie. This should be fixed on master. I will make a release soon.

**Comment by bfolie** [comment]
Thank you @tchaton! The attentiveness with which you are maintaining this repo had made adoption a much easier decision

**Comment by tchaton** [comment]
Thanks for the kind word @bfolie. I hope LitData becomes a useful tool for you and others. Feel free to contribute back, open new issues or feature request.

**Comment by tchaton** [comment]
Also @bfolie. Feel free to join our Discord: https://discord.gg/jdj62zPQ, channel #litdata.
