### ISSUE TITLE
Multiprocessing error when optimizing inside Jupyter notebook

### ISSUE THREAD

**Issue by bfolie** [Lightning-AI/litdata#295]
## 🐛 Bug

I've been doing some prototyping in a Jupyter notebook and am getting errors with Litdata version 0.2.20 and up (0.2.19 works). It seems to occur for any call to `optimize` made from the notebook.

### To Reproduce

Run the following in a Jupyter notebook cell.

```
from lightning.data import optimize

def process(x):
    yield (x,)

optimize(
    fn=process,
    inputs=list(range(100)),
    num_workers=1,
    output_dir="foo",
    chunk_bytes="64MB"
)
```

Error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/brendanfolie/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/brendanfolie/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'process' on <module '__main__' (built-in)>
```

I only see this issue when `optimize` is called from a cell in the Jupyter notebook. I can use Jupyter to invoke a method in a module which itself calls `optimize` and that works fine. Non-Jupyter usage is all working as expected.

### Environment

- Litdata 0.2.20 or 0.2.21 (no problem with 0.2.19 and below)
- ipykernel 6.29.5
- ipython 8.26.0
- jupyter_client 8.6.2
- jupyter_core 5.7.2
- Python 3.11
- OS Ubuntu

### Additional context

Based on the error message this seems to be a [multiprocessing issue](https://github.com/python/cpython/issues/69240#issuecomment-1570569109). Something about version 0.2.20 triggered it. #284 is the only change I see related to multiprocessing, though it's not clear to me why that change would have this effect.

**Comment by tchaton** [comment]
You need to use if __name__ == "__main__"

**Comment by bfolie** [comment]
@tchaton that's not working for me.

It works fine as a script, but not when from a cell in a Jupyter notebook
