### ISSUE TITLE
When using DDP, processes see truncated cached index.json when data is loaded from a mounted network filesystem

### ISSUE THREAD

**Issue by dallmann-uniwue** [Lightning-AI/litdata#351]
## 🐛 Bug

When loading data from a network filesystem (CephFS), processes spawned by DDP sometimes try to load a truncated version of `index.json` from the shared cache, which results in malformed JSON causing an exception and crashing the process. I believe this is linked to the filesystem latency, since it occurs mostly when many jobs are running in the cluster. 

### To Reproduce

The behaviour is really hard to reproduce, since it only occurs spuriously when pointing the StreamingDataset to a folder using the `file:` protocol that resides on a network storage like CephFS. 

### Expected behavior

Each process should see the same version of `index.json` in the cache and load it correctly.

### Environment

- PyTorch Version: 2.3.3
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Python version: 3.11.9
- CUDA/cuDNN version: 12.1.105
- GPU models and configuration: 8xH100, 3xL40s, 8xL40s
- Any other relevant information: Running on-premise on a SLURM cluster

### Additional context

I believe I already tracked the issue to the implementation of [LocalDownloader](https://github.com/Lightning-AI/litdata/blob/3d31c2434735db632ad6e0930bd6507fe75e48d1/src/litdata/streaming/downloader.py#L167). Other implementations of [Downloader](https://github.com/Lightning-AI/litdata/blob/3d31c2434735db632ad6e0930bd6507fe75e48d1/src/litdata/streaming/downloader.py#L27) already use a `FileLock` to prevent multiple processes from copying the same file.

**Comment by dallmann-uniwue** [comment]
I have already implemented a fix that seems to be working (hard to tell without running it for a few days, but I believe this fixes the issue for good): https://github.com/dallmann-uniwue/litdata/commit/a4c51ff42002e643c988ae8416090a3c4f01e5f7

**Comment by tchaton** [comment]
Hey @dallmann-uniwue Would you mind making a PR ?
