### ISSUE TITLE
A contributing.md for the project

### ISSUE THREAD

**Issue by deependujha** [Lightning-AI/litdata#354]
### Motivation

[Roboflow's contributing.md](https://github.com/roboflow/inference/blob/main/CONTRIBUTING.md) is really well structured and to the point.

### Pitch

A simple `contributing.md` file stating the general guidelines and how to setup project and contribute.

**Comment by tchaton** [comment]
We can adapt: https://github.com/Lightning-AI/pytorch-lightning/blob/master/.github/CONTRIBUTING.md
