### ISSUE TITLE
`One of the worker has failed` error in test

### ISSUE THREAD

**Issue by deependujha** [Lightning-AI/litdata#389]
## 🐛 Bug

When CI tests are run, a non-deterministic `RuntimeError: One of the worker has failed` keep coming.

For reference:
- https://github.com/Lightning-AI/litdata/actions/runs/11139472937/job/30956253045
- https://github.com/Lightning-AI/litdata/actions/runs/10898567830/job/30249673425?pr=348
- https://github.com/Lightning-AI/litdata/actions/runs/10905566383/job/30264717145

This is a standard `race condition` issue. 

If the optimize function is too small, then instead of waiting & checking for error_queue, we simply assume that a worker has failed.

https://github.com/Lightning-AI/litdata/blob/main/src/litdata/processing/data_processor.py#L1140

---

### Possible fix 🛠️

IMO, to fix this, we should wait for 0.01 seconds; if no error occurs, everything is fine.

```python
 if all(not w.is_alive() for w in self.workers):
    try:
        error = self.error_queue.get(timeout=0.001)
         self._exit_on_error(error)
    except Empty:
         break
```

---

Thoughts?

cc: @tchaton

**Comment by tchaton** [comment]
Hey @deependujha Yes, let's do that. Also, we could check the return code of the worker to skip the one with 0
