### ISSUE TITLE
Combine Small StreamingDatasets into 1 Large StreamingDataset

### ISSUE THREAD

**Issue by schopra8** [Lightning-AI/litdata#396]
## 🚀 Feature

A primitive that allows users to combine 100s - 1000s of small `StreamingDataset` objects into a single `StreamingDataset` that is serialized to disk / cloud storage.

### Motivation

Right now, we can create `CombinedStreamingDataset` which is great if I want to sample from a small number of datasets. But often, I have 100s or 1000s of small StreamingDatasets that I want combine into a single StreamingDataset, before deleting all the smaller ones.

### Pitch

Write a primitive that can combine N StreamingDatasets into 1 StreamingDataset, using N cores.

### Alternatives

Right now, we use `ld.optimize` to iterate over the N datasets using 1 worker. If we use more than 1 worker, the process fails. This is quite slow.

**Comment by deependujha** [comment]
If all the streaming datasets have similar data, you can try `merge_dataset` utility.

and, btw are you sure what you said about `ld.optimize` in alternative section?

**Comment by tchaton** [comment]
Hey @schopra8. Why does it fail with more than 1 worker ? Can you share the trace ?

**Comment by schopra8** [comment]
vis-a-vis the merge dataset utility, I didn't realize that existed. I'll give that a go later, when we're building our next dataset in the next week or two. 

Additionally, I can circle back with the script we built to merge datasets (where we could only use 1 worker)

**Comment by tchaton** [comment]
Sounds great ! Several users asked for a combined datasets with hundreds of entries. It isn't technically hard to implement. Maybe a good first contribution @schopra8 ;)

**Comment by schopra8** [comment]
Tried this over the weekend and worked like a charm!
