### ISSUE TITLE
`StreamingDataloader` is not split on each rank when training

### ISSUE THREAD

**Issue by Aceticia** [Lightning-AI/litdata#411]
## 🐛 Bug

My `StreamingDataloader`'s length doesn't change when the number of devices change.

### To Reproduce

```python
# Setup dataset
dataset = StreamingDataset(optimized_data_path, shuffle=True, drop_last=True)
train_loader = StreamingDataLoader(
    dataset,
    batch_size=data_config_dict["train_batch_size"],
    num_workers=data_config_dict["num_workers"],
    prefetch_factor=data_config_dict["prefetch_factor"],
    pin_memory=data_config_dict["pin_memory"],
)

# Setup fabric
fabric = L.Fabric(
    precision="bf16-mixed",
    loggers=[logger],
    devices="auto",
    num_nodes=int(os.environ["SLURM_JOB_NUM_NODES"]),
)
fabric.launch()

# Setup dataloader
train_loader = fabric.setup_dataloaders(train_loader)

print(len(train_loader))  # This doesn't change no matter how many GPUs or nodes there are
```

### Expected behavior

When doubling the number of GPUs, the number of batches should half.

### Additional context
If this is the expected behavior and the user is responsible for sharding the dataset themselves, there should ideally be some kind of info on this and some functions to split a streamingdataset by rank.

<details>
  <summary>Environment detail</summary>

- PyTorch Version (e.g., 1.0): 2.5
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.12
- CUDA/cuDNN version: 
- GPU models and configuration: H100
- Any other relevant information:

</details>

**Comment by bhimrazy** [comment]
Hi @Aceticia , Could you pls try by setting strategy to ddp
```python
    fabric = L.Fabric(strategy="ddp")

**Comment by Aceticia** [comment]
Setting the strategy results in the same behavior

**Comment by bhimrazy** [comment]
@Aceticia, could you please also verify if the configuration settings for submitting the job to SLURM are correct? Here’s a guide you can refer to: [Documentation link](https://lightning.ai/docs/fabric/stable/guide/multi_node/slurm.html#submit-a-training-script-to-slurm).

**Comment by Aceticia** [comment]
Yes, I did set the nodes and use srun. These setups should be correct since with pytorch dataloaders and map style datasets the splitting is done as expected.

**Comment by tchaton** [comment]
Hey @Aceticia. You need to instantiate the dataset after the distributed env from pytorch is setup.

**Comment by Aceticia** [comment]
Thank you! Instantiating the dataloader after `fabric.launch()` does solve the issue! This seems to be an important point that isn't explicitly explained in the examples. It would be nice if this is in one of the examples.

**Comment by tchaton** [comment]
Hey @Aceticia. Would you be interested in contributing a simple example ?
