### ISSUE TITLE
Add OCI as an object storage backend for StreamingData

### ISSUE THREAD

**Issue by dkennetzoracle** [Lightning-AI/litdata#416]
## 🚀 Feature

I'd like to add OCI Object Storage as an object storage backend.

### Motivation

I primarily work in Oracle Cloud Infrastructure, and I'd like to leverage lit data StreamingDataset in OCI.

### Pitch

I will contribute an `OCI_STORAGE_AVAILABLE` and `OCIDownloader` with test coverage.

**Comment by bhimrazy** [comment]
Hi @dkennetzoracle,

Thank you for creating this issue!

OCI Object Storage is S3-compatible, so you may be able to connect to it using existing S3 methods. Here’s some documentation that could help:

- [Using the S3-Compatible API with Oracle Object Storage](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm#usingAPI)
- [Example of Configuring AWS SDK for Python](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi_topic-Amazon_S3_Compatibility_API_Support.htm)

  For example:
  
  ```python
  import boto3
    
  s3 = boto3.resource(
      's3',
      aws_access_key_id="your-access-key-id",
      aws_secret_access_key="your-secret-access-key",
      region_name="us-phoenix-1",  # Replace with your region
      endpoint_url="https://<your-namespace>.compat.objectstorage.us-phoenix-1.oraclecloud.com"
  )
    
  # Print out the bucket names
  for bucket in s3.buckets.all():
      print(bucket.name)
  ```

Let us know if this approach works for your implementation.

cc: @tchaton

**Comment by dkennetzoracle** [comment]
@bhimrazy - thanks for the reply - I know how to use boto3, it is just inconvenient because I am not using aws. I'd prefer to authenticate with the provider I am using, and also use their object storage clients. We can close this. Thanks!

**Comment by bhimrazy** [comment]
Thanks for your input, @dkennetzoracle! We totally understand your preference, and happy to share that we'll soon be adding support for **fsspec**, which supports a variety of storage systems, including OCIFS. This will allow you to reference your buckets with `oci://` instead of `s3://` directly.

**Comment by dkennetzoracle** [comment]
@bhimrazy if it's in your backlog, I can take it on as I have cycles outside of work. Would be fun to work on and the project is great. Thanks!

**Comment by bhimrazy** [comment]
@dkennetzoracle, feel free to get started.  
Here’s the PR you can refer to: [PR Link](https://github.com/Lightning-AI/litdata/pull/348).

It was already merged but had to be reverted due to some issues in the multi-node setting.  
Also, feel free to join the Lightning AI community on Discord: [Discord Invite](https://discord.com/invite/MWAEvnC5fU).  
Happy to chat more over there!

**Comment by dkennetzoracle** [comment]
@bhimrazy you helped me today with my litdata question! I'm dk
