### ISSUE TITLE
How to filter some illegal data ?

### ISSUE THREAD

**Issue by kobenaxie** [Lightning-AI/litdata#429]
### Motivation
For example, the sequence is too long(audio), so need to drop this long sequence data, how to implement it ?

**Comment by tchaton** [comment]
Hey @kobenaxie.

You can filter those data during the optimization process.

```
def fn(...):
       data = ....
       if should_keep(data):
                 yield data
       else:
              pass

optimize(
     fn=fn
     ...,
)

**Comment by tchaton** [comment]
@kobenaxie Let me know if you have some issues filtering bad data.

**Comment by kobenaxie** [comment]
Hey @tchaton , thank you for your reply, and I have adopted the first method you advised, it works fine.

**Comment by tchaton** [comment]
Thanks @kobenaxie. Let me add a section in the README for it then.

**Comment by tchaton** [comment]
Hey @kobenaxie: https://github.com/Lightning-AI/litdata/pull/432. done ;)
