### ISSUE TITLE
Pytorch locked to version 2.2.0

### ISSUE THREAD

**Issue by twsl** [Lightning-AI/litdata#47]
### To Reproduce

1. Try to install the latest `torchvision` version 0.17.1 which requires `torch` version 2.2.1, but `litdata` is locked to `torch` version 2.2.0

### Expected behavior

`litdata` works with any `torch` version higher than 2.1.0
i.e. unlock torch version by removing the upper limit

### Environment

- PyTorch Version (e.g., 1.0): 2.2.1
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source): -
- Python version: 3.10
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by tchaton** [comment]
Hey @twsl, have you tried LitData ?
