### ISSUE TITLE
Issue with StreamingDataset when not using all GPUs on host.

### ISSUE THREAD

**Issue by gkroiz** [Lightning-AI/litdata#91]
## 🐛 Bug
When initializing a [StreamingDataset](https://github.com/Lightning-AI/litdata/blob/main/src/litdata/streaming/dataset.py) object, `_DistributedEnv.detect()` is called ([code](https://github.com/Lightning-AI/litdata/blob/main/src/litdata/streaming/dataset.py#L76)) and in the `detect()` function there a world_size check ([code](https://github.com/Lightning-AI/litdata/blob/main/src/litdata/utilities/env.py#L53-L54)). This check fails for my use case when I am not using all GPUs on a host, such that world_size is set to 6 but `torch.cuda.device_count()` will return 8. `6 % 8 != 0`, thus raising the error.

Perhaps this check failure is the intended behavior, but I do not know enough about the `litdata` repository to understand why the code should raise an error when `world_size % device_count != 0`. I would imagine that torch would run various checks when setting up a torch distributed environment, such that this check would not be needed unless it provides a particular purpose to `StreamingDataset()` or another object. If there is any insight here on (1) if this check is needed and (2) why it is needed, that would be great!

### To Reproduce
This issue came up when experimenting with LitGPT. I don't think this section or the following sections are necessary and I will leave the blank for now. Please let me know if any of these sections would help and I can add more description.

#### Code sample
Not needed at the moment.

### Expected behavior
Not needed at the moment.

### Environment
Not needed at the moment.

**Comment by tchaton** [comment]
Hey [gkroiz](https://github.com/gkroiz), do you want to submit a fix for it ?

**Comment by gkroiz** [comment]
I realized that when using `_DistributedEnv.detect()` in a multi-node environment where you are not using all available GPUs, it is not possible (at least with torch), to determine number of nodes. I will create a PR that mentions this.

**Comment by tchaton** [comment]
@gkroiz Lot of great comments. Maybe we could have the following behaviour to unblock you.

By default, we are breaking as we don't have enough information. However, if the user provides extra environement variables: https://github.com/Lightning-AI/pytorch-lightning/tree/master/src/lightning/fabric/plugins/environments, we could accept the execution.

**Comment by gkroiz** [comment]
Yes, I can put together a PR with one of the solutions when I get the time.
